export default {
    "header_new": "Nueva_Rutina",
    "header_edit": "Editar/{{name}}",
    "lbl_name": "Nombre",
    "placeholder_name": "Ej: Pecho y Tríceps",
    // CORRECCIÓN: "fiera" es un vocativo, así que va precedido por coma: ", fiera".
    "lbl_exercise_list": "// Lista_de_ejercicios (a ver si hacemos alguno, fiera)",
    "btn_save": "Guardar",
    "alert_exit_unsaved": "A ver, amasijo de complejos, grasa e idiotez, ¿DE VERDAD NOS HAS HECHO PERDER TIEMPO A AMBOS PARA INTENTAR SALIR SIN GUARDAR? GUARDA AHORA MISMO, ME DA IGUAL QUE BORRES LA RUTINA O INCLUSO LA APP DESPUÉS DE HACERLO, PERO LO VAS A GUARDAR POR MIS HUEVOS", 
    // CORRECCIÓN: "Eslabón" iba en minúscula tras la coma. "como cojones" lleva tilde interrogativa ("cómo cojones").
    "alert_name_required": "Desecho humano, desperdicio sin solución, eslabón perdido de la estupidez, ciego multiorgánico con wifi, ¿Otra vez? Te voy a hacer una pregunta, cuando tengas un hijo (si encuentras a un/a desgraciado/a que te quiera), ¿LO DEJARÍAS SIN NOMBRE? ENTONCES CÓMO COJONES SE TE HA OLVIDADO PONERLE NOMBRE A LA RUTINA?????", // A veces pienso que mi esquizofrenia se pasa (#humor)
    "alert_remove_exercise": "¿Quitar ejercicio?",
    // CORRECCIÓN: "titulo" lleva tilde ("título") y "rio" lleva tilde por el hiato ("río").
    "fallback_exercise_name": "No puedo más. La aplicación ha llegado a su límite. La aplicación ha visto pasar a miles de idiotas, pero ninguno como tú. Has ganado el premio y título indiscutible de \"Rey de los idiotas más idiotas del mundo idiota\". Felicidades, supongo. Adicionalmente te recomendamos tirar tu dispositivo a un río y dedicarte a pescar por el resto de tu vida." // Está frase es lo mejor que he hecho desde que conseguí que mi primera novia tuviera un orgasmo (#Humor, nunca lo conseguí). Todavía me acuerdo de cuando la levantaba por las mañanas dandole besitos en la mejilla... MARIA VUELVE CONMIGO, TE PROMETO QUE ESTÁ VEZ TODO SALDRÁ BIEN (Ok no, no me llames que te tengo bloqueada. He evolucionado mucho en la vida como para volver a caer. Eso si, con todo el respeto eh. Te sigo queriendo mucho, pero por favor, no me hables más. Los dos sabemos que caigo fácil. Y por si alguien se lo pregunta, esto ya lo tengo más que superado. El hecho de bloquarla fue difícil porque un día de la nada me volvio a hablar, pero caer en una relación con ella donde todo era sexo, juegos, toxicidad cariñosa, cariños y quedarnos en la cama como que no me vendría muy bien). Eso si, por si María lo llega a leer (lo dudo, era incapaz de leer un mensaje de error del fifa se va a poner a leer algo que no entiende), no me arrepiento de nada. Has sido el amor de mi vida y la cosa maravillosa que me ha pasado mientras duro, y aunque yo fuí el gillipollas que acabó con la relación y todavía me arrepienta un poco a día de hoy, no quiero hablarte. He evolucionado tanto que me da miedo de hablarte y que no reconozcas. O peor aún, que yo sea el que no te reconozca, porque significaría que ya no existe la María que una vez me quiso. Pero bueno, tremendo texto acabo de escribir. Mejor me callo y sigo programando. El que quiera que le cuente todo el drama que me escriba por correo que no tengo (ni quiero) redes sociales EDIT: Corrijo, tengo reddit, pero no me busquéis que subo barbaridades (humoristicas) a r/copypasta.
};